import { expect, test, loginAs } from './fixtures';

const residentEmail = 'ananya.rao@green-heights.example.test';
const adminEmail = 'meera.desai@green-heights.example.test';

test('email login, role redirects, request refresh, logout and role/ID protection', async ({ page, request }) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto(`/resident/${process.env.E2E_RESIDENT_ID}`);
  await expect(page).toHaveURL('/');
  await expect(page.getByLabel('Resident ID')).toHaveCount(0);
  await page.getByRole('button', { name: residentEmail, exact: true }).click();
  await expect(page.getByLabel('Email address')).toHaveValue(residentEmail);
  await page.getByLabel('Email address').press('Enter');
  await expect(page).toHaveURL(`/resident/${process.env.E2E_RESIDENT_ID}`);
  await expect(page.getByRole('heading', { name: 'Welcome, Ananya Rao.' })).toBeVisible();
  const identity = await page.evaluate(() => JSON.parse(sessionStorage.getItem('anacity.demoUser')!));
  expect(Object.keys(identity).sort()).toEqual(['communityId', 'email', 'id', 'name', 'unitId', 'userType']);
  const moves = (await (await request.get(`${process.env.E2E_API_BASE}/residents/${identity.id}/move-requests`)).json()).data;
  await page.goto(`/resident/${identity.id}/move-requests/${moves[0].id}`);
  await expect(page.getByRole('region', { name: 'Your request at a glance' })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('region', { name: 'Your request at a glance' })).toBeVisible();
  await page.goto(`/resident/00000000-0000-4000-8000-000000000001`);
  await expect(page).toHaveURL(`/resident/${identity.id}`);
  await page.goto(`/admin/${process.env.E2E_ADMIN_ID}/community/${identity.communityId}`);
  await expect(page).toHaveURL(`/resident/${identity.id}`);
  await page.getByRole('button', { name: 'Logout' }).click();
  await expect(page).toHaveURL('/');
  expect(await page.evaluate(() => sessionStorage.getItem('anacity.demoUser'))).toBeNull();
  await loginAs(page, adminEmail);
  await expect(page.getByRole('navigation', { name: 'Workspace' })).toContainText('Welcome, Meera Desai');
  const dashboard = page.url();
  await page.reload();
  await expect(page).toHaveURL(dashboard);
  await expect(page.getByRole('heading', { name: 'Green Heights', exact: true })).toBeVisible();
  await page.goto(`/resident/${identity.id}`);
  await expect(page).toHaveURL(dashboard);
  await page.goto(`/admin/${process.env.E2E_ADMIN_ID}/community/00000000-0000-4000-8000-000000000001`);
  await expect(page).toHaveURL(dashboard);
  await page.getByRole('button', { name: 'Logout' }).click();
  await expect(page).toHaveURL('/');
  await page.goBack();
  await expect(page).toHaveURL('/');
  expect(errors).toEqual([]);
});

test('friendly errors, loading protection, corrupt session and mobile login', async ({ page }) => {
  await page.goto('/');
  await page.evaluate(() => sessionStorage.setItem('anacity.demoUser', '{corrupt'));
  await page.goto(`/resident/${process.env.E2E_RESIDENT_ID}`);
  await expect(page).toHaveURL('/');
  expect(await page.evaluate(() => sessionStorage.getItem('anacity.demoUser'))).toBeNull();
  await page.getByRole('button', { name: 'Continue' }).click();
  await expect(page.getByRole('alert')).toHaveText('Enter your email address.');
  expect(await page.getByRole('alert').evaluate((element) => getComputedStyle(element).color)).toBe('rgb(185, 28, 28)');
  await page.getByLabel('Email address').fill('not-an-email');
  await page.getByRole('button', { name: 'Continue' }).click();
  await expect(page.getByRole('alert')).toHaveText('Enter a valid email address.');
  await page.getByLabel('Email address').fill('unknown@example.test');
  await page.getByRole('button', { name: 'Continue' }).click();
  await expect(page.getByRole('alert')).toHaveText('No account found for this email.');
  let release: () => void = () => {};
  const held = new Promise<void>((resolve) => { release = resolve; });
  let calls = 0;
  await page.route('**/api/demo/login', async (route) => { calls++; await held; await route.abort(); });
  await page.getByLabel('Email address').fill(residentEmail);
  await page.getByRole('button', { name: 'Continue' }).click();
  await expect(page.getByRole('button', { name: 'Signing in...' })).toBeDisabled();
  expect(calls).toBe(1);
  release();
  await expect(page.getByRole('alert')).toHaveText('Unable to connect to the server. Please try again.');
  expect(await page.getByRole('alert').evaluate((element) => getComputedStyle(element).color)).toBe('rgb(185, 28, 28)');
  await page.unroute('**/api/demo/login');
  await page.route('**/api/demo/login', (route) => route.fulfill({ status: 500, json: { message: 'SQL should not be shown' } }));
  await page.getByRole('button', { name: 'Continue' }).click();
  await expect(page.getByRole('alert')).toHaveText('Something went wrong. Please try again.');
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/email-login-mobile.png', fullPage: true });
});
