import { expect, test, loginAs } from './fixtures';

const residentId = process.env.E2E_RESIDENT_ID;
const adminId = process.env.E2E_ADMIN_ID;
const api = process.env.E2E_API_BASE;
test.beforeEach(async ({ page }) => { await loginAs(page, 'ananya.rao@green-heights.example.test'); });
test.beforeAll(() => { expect(residentId && adminId && api, 'Run via the root test:frontend script with a dedicated empty test database').toBeTruthy(); });

test('resident move-in: chat, fields, documents, submit, requested changes and resubmit', async ({ page, request }) => {
  const pageErrors: string[] = [];
  page.on('pageerror', (error) => pageErrors.push(error.message));
  await page.goto(`/resident/${residentId}`);
  await expect(page.getByRole('heading', { name: 'Welcome, Ananya Rao.' })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Request summary' })).toContainText('Total requests');
  await page.getByRole('button', { name: '+ New move-in request', exact: true }).click();
  await expect(page).toHaveURL(/\/move-requests\/[0-9a-f-]+$/);
  const id = page.url().split('/').at(-1);
  await expect(page.getByRole('heading', { name: 'Edit details', exact: true })).toBeVisible();
  await page.getByLabel('Your message').fill('Please note: use the service lift.');
  await page.getByRole('button', { name: 'Send message' }).click();
  await expect(page.getByLabel('Notes', { exact: false })).toHaveValue('Use the service lift.');
  await expect(page.getByLabel('Moving company', { exact: false })).toHaveCount(0);
  await expect(page.getByRole('heading', { name: 'Supporting Documents (Optional)', exact: true })).toBeVisible();
  await expect(page.getByLabel('Required documents', { exact: true })).toHaveCount(0);
  await expect(page.getByLabel('Conversation messages')).toContainText('I have recorded your note');
  await expect(page.getByLabel('Conversation messages')).toContainText('Please note: use the service lift.');
  await expect(page.getByRole('button', { name: 'Send message' })).toHaveText('Send message');
  await page.getByLabel('Your message').fill('simulate failure');
  await page.getByRole('button', { name: 'Send message' }).click();
  const assistantError = page.getByRole('region', { name: 'Move assistant' }).locator('.assistant-fallback');
  await expect(assistantError).toBeVisible();
  expect(await assistantError.evaluate((element) => getComputedStyle(element).color)).toBe('rgb(185, 28, 28)');
  await expect(page.getByRole('link', { name: 'Continue with request details' })).toBeVisible();
  await expect(page.getByLabel('Moving company', { exact: false })).toHaveCount(0);
  await expect(page.getByLabel('Your message')).toHaveValue('simulate failure');
  await page.getByLabel('Your message').fill('');
  await expect(page.getByRole('button', { name: 'Submit request', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Submit request', exact: true }).click();
  await expect(page.locator('#error-requestedDate')).toContainText('Requested date is required');
  await expect(page.locator('[id^="error-documents."]')).toHaveCount(0);
  await page.getByLabel('Your message').fill("I'm moving next Saturday morning.");
  await page.getByRole('button', { name: 'Send message' }).click();
  await expect(page.getByLabel('Conversation messages')).toContainText('Shall I use');
  await expect(page.getByLabel('Requested date', { exact: false })).toHaveValue('');
  await page.getByLabel('Your message').fill('Yes.');
  await page.getByRole('button', { name: 'Send message' }).click();
  await expect(page.getByLabel('Requested date', { exact: false })).toHaveValue(/\d{4}-\d{2}-\d{2}/);
  await expect(page.getByLabel('Time slot', { exact: false })).toHaveValue('09:00-12:00');
  await page.getByLabel('Requested date', { exact: false }).fill('2026-09-07');
  await page.getByLabel('Time slot', { exact: false }).selectOption('09:00-12:00');
  await page.getByLabel('Vehicle count').fill('1');
  await page.getByLabel('Occupant count').fill('2');
  await page.getByLabel('Vehicle details', { exact: false }).fill('invalid JSON');
  await page.getByRole('button', { name: 'Save details' }).click();
  await expect(page.locator('#error-vehicleDetails')).toContainText('valid JSON');
  await page.getByLabel('Vehicle details', { exact: false }).fill('[{"registration":"KA01AB1234"}]');
  await page.getByRole('button', { name: 'Save details' }).click();
  await expect(page.getByRole('status')).toContainText('Request details saved.');
  for (const type of ['IDENTITY_DOCUMENT']) {
    await page.getByLabel('Document type', { exact: true }).fill(type);
    await page.getByLabel('File URL', { exact: true }).fill(`https://example.test/${type}.pdf`);
    await page.getByRole('button', { name: 'Add document', exact: true }).click();
    await expect(page.getByLabel('File URL', { exact: true })).toHaveValue('');
  }
  const documents = page.getByRole('region', { name: 'Supporting Documents (Optional)', exact: true });
  await documents.getByRole('button', { name: 'Replace', exact: true }).first().click();
  await page.getByLabel('New file URL').fill('https://example.test/replacement.pdf');
  await page.getByRole('button', { name: 'Save replacement' }).click();
  await expect(page.getByRole('status')).toContainText('Document replaced.');
  await documents.getByRole('button', { name: 'Delete', exact: true }).first().click();
  await page.getByRole('button', { name: 'Confirm delete' }).click();
  await expect(page.getByRole('status')).toContainText('Document deleted.');
  // Optional supporting documents retain the generic add/replace/delete workflow.
  await page.getByLabel('Document type', { exact: true }).fill('IDENTITY_DOCUMENT');
  await page.getByLabel('File URL', { exact: true }).fill('https://example.test/identity.pdf');
  await page.getByRole('button', { name: 'Add document', exact: true }).click();
  await expect(page.getByText('✓ Ready to submit', { exact: true })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Move assistant' })).not.toContainText('Vehicle count is required');
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: 'test-results/resident-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Submit request', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Request submitted.');
  await expect(page.getByRole('heading', { name: 'Edit details', exact: true })).toHaveCount(0);
  await expect(documents.getByRole('button', { name: 'Delete', exact: true })).toHaveCount(0);
  const review = await request.post(`${api}/admin/move-requests/${id}/review`, { data: { adminId } });
  expect(review.status()).toBe(200);
  const uploaded = await (await request.get(`${api}/move-requests/${id}/documents`)).json();
  const identityDocument = uploaded.data.find((document: { documentType: string }) => document.documentType === 'IDENTITY_DOCUMENT');
  expect((await request.post(`${api}/admin/move-requests/${id}/documents/${identityDocument.id}/reject`, {
    data: { adminId, reason: 'Identity document is unclear.' },
  })).status()).toBe(200);
  const change = await request.post(`${api}/admin/move-requests/${id}/request-changes`, { data: { adminId, reason: 'Please confirm the vehicle registration.' } });
  expect(change.status()).toBe(200);
  await page.reload();
  await expect(page.getByRole('region', { name: 'Changes requested' })).toContainText('Please confirm the vehicle registration.');
  await expect(page.getByRole('region', { name: 'Changes requested' })).not.toContainText('Replace rejected documents');
  const rejectedDocument = documents.locator('.document-row').filter({ hasText: 'Identity document' });
  await expect(rejectedDocument).toContainText('Rejected');
  await rejectedDocument.getByRole('button', { name: 'Replace', exact: true }).click();
  await page.getByLabel('New file URL').fill('https://example.test/clear-identity.pdf');
  await page.getByRole('button', { name: 'Save replacement' }).click();
  await expect(rejectedDocument).toContainText('Uploaded');
  await page.getByLabel('Message to your community').fill('I have replaced the identity document.');
  await page.getByRole('button', { name: 'Add comment', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Updates & activity' })).toContainText('I have replaced the identity document.');
  await page.getByLabel('Notes', { exact: false }).fill('Registration confirmed: KA01AB1234.');
  await page.getByRole('button', { name: 'Save details' }).click();
  await expect(page.getByRole('status')).toContainText('Request details saved.');
  await page.getByRole('button', { name: 'Resubmit request' }).click();
  await expect(page.getByRole('status')).toContainText('Request submitted.');
  await expect(page.getByRole('region', { name: 'Updates & activity' })).toContainText('Resubmitted');
  const persisted = await (await request.get(`${api}/move-requests/${id}`)).json();
  expect(persisted.data.status).toBe('SUBMITTED');
  expect(persisted.data.details.notes).toContain('Registration confirmed');
  await page.getByRole('link', { name: 'Back to dashboard' }).click();
  await expect(page.getByRole('region', { name: 'Notifications' })).toContainText('Please confirm the vehicle registration.');
  expect(pageErrors).toEqual([]);
});

test('empty dashboard identity, unavailable assistant and Marina move-out configuration', async ({ page, request }) => {
  await loginAs(page, 'new-resident@example.test');
  await page.goto(`/resident/${process.env.E2E_EMPTY_RESIDENT_ID}`);
  await expect(page.getByRole('heading', { name: 'Welcome, New Resident.' })).toBeVisible();
  await expect(page.locator('.page-heading')).toContainText('Green Heights · Unit A-101');
  await expect(page.getByText('Your next move starts here.')).toBeVisible();
  await page.route('**/api/agent/health', (route) => route.fulfill({ json: { agentConfigured: false, provider: 'openai' } }));
  await loginAs(page, 'arjun.iyer@marina-residence.example.test');
  await page.goto(`/resident/${process.env.E2E_MARINA_RESIDENT_ID}`);
  await page.getByRole('button', { name: '+ New move-out request', exact: true }).click();
  await expect(page.getByText('The assistant is temporarily unavailable.', { exact: false })).toBeVisible();
  await expect(page.getByLabel('Moving company', { exact: true })).toHaveCount(0);
  await expect(page.getByLabel('Time slot', { exact: false })).toContainText('08:00-11:00');
  await expect(page.getByLabel('Time slot', { exact: false })).not.toContainText('09:00-12:00');
  await expect(page.getByRole('heading', { name: 'Supporting Documents (Optional)', exact: true })).toBeVisible();
  await expect(page.getByLabel('Required documents', { exact: true })).toHaveCount(0);
  const fallback = page.getByRole('alert').filter({ hasText: 'The assistant is temporarily unavailable.' });
  expect(await fallback.evaluate((element) => getComputedStyle(element).color)).toBe('rgb(185, 28, 28)');
  await page.getByLabel('Requested date', { exact: false }).fill('2026-09-07');
  await page.getByLabel('Time slot', { exact: false }).selectOption('08:00-11:00');
  await page.getByRole('button', { name: 'Save details' }).click();
  await expect(page.getByRole('status')).toContainText('Request details saved.');
  await expect(page.getByText('✓ Ready to submit', { exact: true })).toBeVisible();
  const id = page.url().split('/').at(-1);
  await page.getByRole('button', { name: 'Submit request', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Request submitted.');
  const saved = await (await request.get(`${api}/move-requests/${id}`, { headers: { 'X-Resident-Id': process.env.E2E_MARINA_RESIDENT_ID! } })).json();
  expect(saved.data.status).toBe('SUBMITTED');
  expect(saved.data.details.movingCompany).toBeNull();
  expect(saved.data.type).toBe('MOVE_OUT');
  expect(saved.data.documents).toEqual([]);
});

test('mobile move-out and ownership/error states', async ({ page, request }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`/resident/${residentId}`);
  await page.getByRole('button', { name: '+ New move-out request', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Move out request', exact: true })).toBeVisible();
  await expect(page.getByLabel('Moving company', { exact: false })).toHaveCount(0);
  await expect(page.getByLabel('Occupant count', { exact: true })).toBeVisible();
  const assistant = await page.getByRole('region', { name: 'Move assistant' }).boundingBox();
  const progress = await page.getByRole('region', { name: 'Your request at a glance' }).boundingBox();
  expect(progress!.y).toBeGreaterThan(assistant!.y + assistant!.height);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/resident-mobile.png', fullPage: true });
  const id = page.url().split('/').at(-1);
  const result = await (await request.get(`${api}/move-requests/${id}`)).json();
  expect(result.data.type).toBe('MOVE_OUT');
  await page.goto(`/resident/${residentId!.toUpperCase()}/move-requests/${id}`);
  await expect(page.getByRole('heading', { name: 'Move out request', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Edit details', exact: true })).toBeVisible();
  await page.goto(`/resident/00000000-0000-4000-8000-000000000001/move-requests/${id}`);
  await expect(page).toHaveURL(`/resident/${residentId}`);
  await page.goto('/resident/invalid-id');
  await expect(page).toHaveURL(`/resident/${residentId}`);
});

test('demo identity selection and resident cancellation', async ({ page, request }) => {
  await page.goto('/');
  await page.getByRole('button', { name: '+ New move-out request', exact: true }).click();
  await page.waitForURL(/\/move-requests\/[0-9a-f-]+$/);
  const id = page.url().split('/').at(-1);
  await page.getByRole('button', { name: 'Cancel request', exact: true }).click();
  await page.getByLabel('Cancellation reason').fill('Moving plans postponed.');
  page.once('dialog', (dialog) => dialog.dismiss());
  await page.getByRole('button', { name: 'Confirm cancellation' }).click();
  expect((await (await request.get(`${api}/move-requests/${id}`)).json()).data.status).toBe('DRAFT');
  page.once('dialog', (dialog) => dialog.accept());
  await page.getByRole('button', { name: 'Confirm cancellation' }).click();
  await expect(page.getByRole('status')).toContainText('Request cancelled.');
  await expect(page.getByRole('heading', { name: 'Edit details' })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Submit request', exact: true })).toHaveCount(0);
  await expect(page.getByRole('region', { name: 'Updates & activity' })).toContainText('Moving plans postponed.');
  await page.reload();
  await expect(page.getByRole('button', { name: 'Cancel request', exact: true })).toHaveCount(0);
});
